config/routes.rb
Rails.application.routes.draw do
  get 'homepage/home'
  # get '/login', to: 'sessions#new'
  # post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  resources :books do 
    resources :reviews, shallow: true 
  end

  resources :reviews
  resources :books, only: [:index, :show]
  resources :genres, only: [:index, :show]
  resources :authors, only: [:index, :show]
  resources :users
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord

    has_many :books
    has_many :genres, through: :books 

    # validates :author, presence: true 
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  has_many :reviews, dependent: :destroy

 

  def avg_rating
    array = []
    self.reviews.each do |r|
      array << r.rating
    end
    sum = array.inject(0){|sum, x| sum + x }
    total = sum.to_f / array.length.to_f
    total.to_f
  end


end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :books
    has_many :authors, through: :books 

    # validates :genre, presence: true 
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  validates :rating, presence: true 
  validates :message, presence: true 
end

app/models/user.rb
class User < ApplicationRecord

    has_many :reviews, dependent: :destroy
    has_many :books, through: :reviews 
    has_secure_password

    validates :name, uniqueness: true
    validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    before_action :require_login

    def log_in_user(user_id)
        session[:user_id] = user_id
    end

    def current_user 
        # @current_user ||= User.find_by(id: session[:user_id])
        session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_login 
        unless logged_in?
            redirect_to new_session_path
        end
    end


end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

    before_action :find_author, only: [:show]

   

    def index
        @authors = Author.all 
    end

    def show 

    end

    private 

    def find_author
        @author = Author.find(params[:id])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    skip_before_action :require_login
    before_action :find_book, only: [:show]


    # skip_before_action :require

    def index
        @books = Book.all 
    end

    def show 

    end

    private 

    def find_book
        @book = Book.find(params[:id])
    end

    # def book_params
    #     params.require(:book).permit(:title, :author_id, :genre_id )
    # end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    before_action :find_genre, only: [:show]

    

    def index
        @genres = Genre.all 
    end

    def show 

    end

    private

    def find_genre 
        @genre = Genre.find(params[:id])
    end

end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  skip_before_action :require_login
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :find_review, only: [:edit, :update, :destroy]

    before_action :set_user_book, only: [:new, :create, :edit, :update]

    

    def new
        @review = Review.new
        @book = Book.find_by_id(params[:book_id])
        # id = params[:book_id]
        # if id && @book = Book.find_by_id(id)
        #     @review = @book.review.build 
        # else  
        #     @review = current_user.reviews.build
        # end
        # if @book
        #     @review = @book.reviews.new
        # else  
        #     @review = current_user.reviews.new

        # end
    end

    def create
        @review = Review.new(review_params)
        @review.user_id = current_user
        @review.book_id = params[:book_id]
        if @review.save
            redirect_to @review.book
        else   
            render :new
        end
        # @review = current_user.reviews.build(review_params)
        # if @review.save 
        #     redirect_to @review.book
        # else  
        #     render :new 
        # end
    end

    def edit 
    end

    def update 
        @review.update(review_params)
        @review.user_id = current_user 
        if @review.save
            redirect_to @review.book
        else  
            render :edit 
        end
    end

    def destroy
        @review.destroy 
        redirect_to user_path(@review.user)
    end

    private

    def set_user_book
        @books = Book.all
        @users = User.all
    end

    def find_review
        @review = Review.find(params[:id])
    end

    def review_params
        params.require(:review).permit(:message, :rating)
    end

    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :require_login, only: [:new, :create]

    def new 
    end

    def create 
        user = User.find_by(name: params[:name])
        if user && user.authenticate(params[:password])
            log_in_user(user.id)
            redirect_to user_path(user)
        else 
            flash[:error] = 'Invalid email/password combination'
            render :new 
        end
    end

    def destroy
        session.destroy
        redirect_to new_session_path 
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only: [:show, :destroy]

    skip_before_action :require_login, only: [:new, :create, :destroy]

    def show
    end

    def new 
        @user = User.new 
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            log_in_user(@user.id)
            redirect_to user_path(@user)
        else  
            render :new 
        end
    end

    def destroy 
        @user.destory 
        redirect_to new_session_path
    end

    private 

    def find_user
        @user = User.find(params[:id])
    end

    def user_params 
        params.permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/log_in_helper.rb
module LogInHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authors/index.html.erb
<h1>List of Authors</h1>

<% @authors.each do |a| %>
<h4>Name: <%= link_to a.name, a %> </h2>
<%end%>

app/views/authors/show.html.erb
<h1>Author's Profile</h1>

<h2>Name: <%= @author.name %> </h2>

<h3>Books: </h3>
<ul>
    <% @author.books.each do |b| %>
        <li><%= b.title %></li>
    <%end%>
</ul>

app/views/books/index.html.erb
<div class ="container">
<p> Books that need your review : </p>
<ul class="list-group list-group-flush">
<% @books.each do |b| %>
  <li class="list-group-item disabled"><%= link_to b.title, b %> | Rating: <%= b.avg_rating %></li>
</ul>
<%end%>
</div>

app/views/books/show.html.erb
<div class = "container">
<h1> <%= @book.title %> </h1>

<h4>Author: <%= @book.author.name %> </h4>
<h4>Genre: <%= @book.genre.name %> </h4>

<h4>Rating: <%= @book.avg_rating %></h4>

<h4>Reviews: </h4>
<ul>
<% @book.reviews.each do |r| %>
    <li><h5><%=r.user.name%></h5> <%= r.message %></li>
<%end%>
</ul>

<button><%= link_to "Add Review", new_book_review_path(@book) %></button>
<button><%= link_to "Back", books_path%></button>

</div>

app/views/genres/index.html.erb
<h1>List of Genres</h1>

<% @genres.each do |g| %>
<h3> <%= link_to g.name, g %> </h3>
<%end%>

app/views/genres/show.html.erb
<h1> <%= @genre.name %> </h1>

<% @genre.books.each do |b| %>
<h4> Book Title: <%= b.title %> </h4>
<%end%>

app/views/users/new.html.erb
<div class= "container p-10">
<h1>Create an Account</h1>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
        <div class="text-danger"> <%= msg %> </div>
    <%end%> 
<%end%>
<%= form_tag ({controller: 'users', action: 'create', method: 'post'}) do %>
    <div>
        <%= label_tag "Name" %>
        <%= text_field_tag :name, params[:name] %>
    </div>
    <div>
        <%= label_tag "Password" %>
        <%= password_field_tag :password, params[:password] %>
    </div>
    <%= submit_tag "Signup" %>
<% end %>
</div>

app/views/users/show.html.erb
<div class = "container">
<div class="card text-center style="width: 18rem;">
<div class="card-body">
  <h5 class="card-title">Welcome <%= @user.name %>!</h5>
  <% @user.reviews.each do |b| %>
  <h6 class="card-subtitle mb-2 ">Book Title: <%= b.book.title %>: </h6>
  <h6 class="card-subtitle mb-2 ">Rating: <%= b.rating %> </h6>
  <div class="card-text mb-2"> Review: <%= b.message %></div>
  <a href="#" class="card-link"><button><%= link_to "Edit", edit_review_path(b)%></button></a> <br>
  <a href="#" class="card-link"><%= button_to "Delete", b, method: :delete%></a> <br>
  <% end %> 
</div>
</div>
</div>