config/routes.rb
Rails.application.routes.draw do
  get 'homepage/home'
  # get '/login', to: 'sessions#new'
  # post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'

  resources :books do 
    resources :reviews, shallow: true 
  end

  resources :reviews
  resources :books, only: [:index, :show]
  resources :genres, only: [:index, :show]
  resources :authors, only: [:index, :show]
  resources :users
  resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord

    has_many :books
    has_many :genres, through: :books 

    # validates :author, presence: true 
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :genre
  has_many :reviews, dependent: :destroy

 

  def avg_rating
    array = []
    self.reviews.each do |r|
      array << r.rating
    end
    sum = array.inject(0){|sum, x| sum + x }
    total = sum.to_f / array.length.to_f
    total.to_f
  end


end

app/models/genre.rb
class Genre < ApplicationRecord

    has_many :books
    has_many :authors, through: :books 

    # validates :genre, presence: true 
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  validates :rating, presence: true 
  validates :message, presence: true 
end

app/models/user.rb
class User < ApplicationRecord

    has_many :reviews, dependent: :destroy
    has_many :books, through: :reviews 
    has_secure_password

    validates :name, uniqueness: true
    validates :name, presence: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

    before_action :find_author, only: [:show]

   

    def index
        @authors = Author.all 
    end

    def show 

    end

    private 

    def find_author
        @author = Author.find(params[:id])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    skip_before_action :require_login
    before_action :find_book, only: [:show]


    # skip_before_action :require

    def index
        @books = Book.all 
    end

    def show 

    end

    private 

    def find_book
        @book = Book.find(params[:id])
    end

    # def book_params
    #     params.require(:book).permit(:title, :author_id, :genre_id )
    # end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

    before_action :find_genre, only: [:show]

    

    def index
        @genres = Genre.all 
    end

    def show 

    end

    private

    def find_genre 
        @genre = Genre.find(params[:id])
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :find_review, only: [:edit, :update, :destroy]

    before_action :set_user_book, only: [:new, :create, :edit, :update]

    

    def new
        @review = Review.new
        @book = Book.find_by_id(params[:book_id])
        # id = params[:book_id]
        # if id && @book = Book.find_by_id(id)
        #     @review = @book.review.build 
        # else  
        #     @review = current_user.reviews.build
        # end
        # if @book
        #     @review = @book.reviews.new
        # else  
        #     @review = current_user.reviews.new

        # end
    end

    def create
        @review = Review.new(review_params)
        @review.user_id = current_user
        @review.book_id = params[:book_id]
        if @review.save
            redirect_to @review.book
        else   
            render :new
        end
        # @review = current_user.reviews.build(review_params)
        # if @review.save 
        #     redirect_to @review.book
        # else  
        #     render :new 
        # end
    end

    def edit 
    end

    def update 
        @review.update(review_params)
        @review.user_id = current_user 
        if @review.save
            redirect_to @review.book
        else  
            render :edit 
        end
    end

    def destroy
        @review.destroy 
        redirect_to user_path(@review.user)
    end

    private

    def set_user_book
        @books = Book.all
        @users = User.all
    end

    def find_review
        @review = Review.find(params[:id])
    end

    def review_params
        params.require(:review).permit(:message, :rating)
    end

    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :find_user, only: [:show, :destroy]

    skip_before_action :require_login, only: [:new, :create, :destroy]

    def show
    end

    def new 
        @user = User.new 
    end

    def create 
        @user = User.new(user_params)
        if @user.save
            log_in_user(@user.id)
            redirect_to user_path(@user)
        else  
            render :new 
        end
    end

    def destroy 
        @user.destory 
        redirect_to new_session_path
    end

    private 

    def find_user
        @user = User.find(params[:id])
    end

    def user_params 
        params.permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/log_in_helper.rb
module LogInHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BOOK RAIDERS</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Sarabun:ital,wght@1,200&display=swap" rel="stylesheet">

    <nav class="navbar navbar-expand-lg">
    <a class="navbar-brand" href="#"><%= link_to "BOOK RAIDERS", books_path%></a>
    <a class= "navbar" href="#"> <%= link_to "home", homepage_home_path %> </a>
    <nav class="navbar navbar-expand justify-content-between">
</nav>

    <form class="form-inline">
    <% if current_user.nil? %>
    <a class="navbar-brand" href="#"> <%= link_to "Login",new_session_path%> 
    </a>
    <a class="navbar-brand" href="#"> <%= link_to "Signup", new_user_path %>
    </a>
  <%else%>
  <form class="form-inline">
  <div style="padding-left: 10px;">
    <a class= "navbar-brand" href= "#"> <%=link_to "Profile", user_path(current_user) %>
    </a>
    <a class="navbar-brand" href="#"> <%= link_to "Log Out", logout_path, method: "delete" %>
    </a>
  <%end%> 
    </div>
    </div>
    </form>
  </form>
  </nav>


  <div class="jumbotron jumbotron-fluid" "background-size: 100%;">
  <div class="container for-about">
  <div class="container">
    <h1 class="text-center" "display-4"></h1>
    <p class="text-center"> [ BEWARE AUTHORS ] </p>
  </div>
</div>

  <body>
    <% if flash %>
      <% flash.each do |key, msg| %>
        <div class= "<%= key %>">
        <%= msg %>
        </div>
      <% end%>
    <% end %>

    
    
    <%= yield %>
  </body>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>

  <footer class="text-center text-lg-start">
  <div class="container p-4">
        <div class = "text-center p-3">
  
          whatcha gonna do when the BOOK RAIDERS come for you? <br>
            © 2021 Harrf + Syd
  </div>
</footer>
</html>